services:
  - type: web
    name: asaan-store
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /robots.txt
    envVars:
      - key: APP_NAME
        value: Akbari Development Group
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: CARTXIS_ADMIN_NAME
        sync: false
      - key: CARTXIS_ADMIN_EMAIL
        sync: false
      - key: CARTXIS_ADMIN_PASSWORD
        sync: false
      - key: CARTXIS_THEME_DIRECTORY_URL
        value: https://cartxis.com/api
      - key: CARTXIS_THEME_API_KEY
        sync: false
      - key: QUEUE_CONNECTION
        value: sync
      - key: CACHE_STORE
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: FILESYSTEM_DISK
        value: local
      - key: MAIL_MAILER
        value: log
      - key: APP_KEY
        sync: false
